export const OFFICIAL_SUBJECTS: Record<string, string[]> = {
    "ZULHL": ["isiZulu Home Language", "Zulu Home Language"],
    "XHHL": ["isiXhosa Home Language", "Xhosa Home Language"],
    "AFHL": ["Afrikaans Home Language"],
    "ENGHL": ["English Home Language"],
    "SOTHO": ["Sesotho", "Sesotho Home Language"],
    "NSOTHO": ["Northern Sotho", "Sepedi"],
    "SSOTHO": ["Southern Sotho"],
    "SETSWANA": ["Setswana", "Tswana"],
    "XITSONGA": ["Xitsonga", "Tsonga"],
    "TSHIVENDA": ["Tshivenda", "Venda"],
    "ENGFA": ["English First Additional Language"],
    "ENGLA": ["English Second Additional Language"],
    "MATH": ["Mathematics"],
    "MATHLIT": ["Mathematical Literacy"],
    "LIFE": ["Life Sciences"],
    "PHYS": ["Physical Sciences"],
    "CHEM": ["Chemistry"],
    "BIOLOGY": ["Biology"],
    "GEOG": ["Geography"],
    "HIST": ["History"],
    "BUSINESS": ["Business Studies"],
    "ACCOUNTING": ["Accounting"],
    "ECONOMICS": ["Economics"],
    "CAT": ["Computer Applications Technology"],
    "IT": ["Information Technology"],
    "LIFEOR": ["Life Orientation"],
    "AGRIC": ["Agricultural Sciences"],
    "TOURISM": ["Tourism"],
    "CONSUMER": ["Consumer Studies"],
    "DRAAD": ["Dramatic Arts"],
    "MUSIC": ["Music"],
    "VISUAL": ["Visual Arts"],
}

export const ACHIEVEMENT_LEVELS = {
    8: { min: 0, max: 29, label: "Not Achieved" },
    7: { min: 30, max: 39, label: "Elementary Achievement" },
    6: { min: 40, max: 49, label: "Moderate Achievement" },
    5: { min: 50, max: 59, label: "Adequate Achievement" },
    4: { min: 60, max: 69, label: "Substantial Achievement" },
    3: { min: 70, max: 79, label: "Meritorious Achievement" },
    2: { min: 80, max: 89, label: "Outstanding Achievement" },
    1: { min: 90, max: 100, label: "Outstanding Achievement" },
}

export const OFFICIAL_STATISTICS = {
    overallPassRate: 87.3,
    bachelorPassRate: 47.8,
    mathematicsPassRate: 69.1,
    physicalSciencesPassRate: 75.6,
    distinctionRate: 10.8,
}

export const HOME_LANGUAGES = [
    "English Home Language",
    "Afrikaans Home Language",
    "IsiZulu Home Language",
    "IsiXhosa Home Language",
    "Sepedi Home Language",
    "Sesotho Home Language",
    "Setswana Home Language",
    "Tshivenda Home Language",
    "Xitsonga Home Language",
    "SiSwati Home Language",
]

export const FIRST_ADDITIONAL_LANGUAGES = [
    "English First Additional Language",
    "Afrikaans First Additional Language",
    "IsiZulu First Additional Language",
    "IsiXhosa First Additional Language",
    "Sepedi First Additional Language",
    "Sesotho First Additional Language",
    "Setswana First Additional Language",
    "Tshivenda First Additional Language",
    "Xitsonga First Additional Language",
    "SiSwati First Additional Language",
]
