export const SUBJECTS = [
    "Mathematics",
    "Mathematical Literacy",
    "Physical Sciences",
    "Life Sciences",
    "English Home Language",
    "English First Additional Language",
    "Afrikaans Home Language",
    "Afrikaans First Additional Language",
    "IsiZulu Home Language",
    "IsiZulu First Additional Language",
    "IsiXhosa Home Language",
    "IsiXhosa First Additional Language",
    "Sepedi Home Language",
    "Sepedi First Additional Language",
    "Setswana Home Language",
    "Setswana First Additional Language",
    "Sesotho Home Language",
    "Sesotho First Additional Language",
    "Xitsonga Home Language",
    "Xitsonga First Additional Language",
    "SiSwati Home Language",
    "SiSwati First Additional Language",
    "Tshivenda Home Language",
    "Tshivenda First Additional Language",
    "isiNdebele Home Language",
    "isiNdebele First Additional Language",
    "Accounting",
    "Business Studies",
    "Economics",
    "Geography",
    "History",
    "Life Orientation",
    "Information Technology",
    "Computer Applications Technology",
    "Agricultural Sciences",
    "Engineering Graphics and Design",
    "Visual Arts",
    "Dramatic Arts",
    "Music",
    "Tourism",
    "Consumer Studies",
]
