import { NextResponse } from "next/server"

export const revalidate = 0

interface Bursary {
  id: string
  title: string
  provider: string
  amount: string
  field: string
  description: string
  eligibility: string[]
  deadline: string
  link: string
}

// Server-side cache with 24-hour TTL
let bursariesCache: { data: Bursary[]; timestamp: number } | null = null
const CACHE_DURATION = 24 * 60 * 60 * 1000 // 24 hours

const BURSARIES_DATA: Bursary[] = [
  {
    id: "bursary-1",
    title: "Eskom Engineering Bursary",
    provider: "Eskom Holdings SOC Ltd",
    amount: "R80,000 per year",
    field: "Electrical Engineering",
    description: "Comprehensive bursary covering tuition, accommodation, and study materials for engineering students",
    eligibility: [
      "South African citizen",
      "Grade 12 with Mathematics and Physical Science",
      "Minimum 70% average",
      "Financial need",
    ],
    deadline: "30 September 2025",
    link: "https://www.eskom.co.za/bursaries",
  },
  {
    id: "bursary-2",
    title: "Sasol Engineering Bursary",
    provider: "Sasol Limited",
    amount: "R75,000 per year",
    field: "Chemical Engineering",
    description: "Full bursary for chemical engineering students with excellent academic records",
    eligibility: [
      "South African citizen",
      "Minimum 65% for Mathematics and Physical Science",
      "Enrolled at a South African university",
      "Commitment to work for Sasol",
    ],
    deadline: "31 August 2025",
    link: "https://www.sasol.com/careers/bursaries",
  },
  {
    id: "bursary-3",
    title: "NSFAS Bursary",
    provider: "National Student Financial Aid Scheme",
    amount: "Full tuition coverage",
    field: "All Fields",
    description: "Government-funded financial aid for students from low-income households",
    eligibility: [
      "South African citizen",
      "Combined household income below R350,000",
      "Registered at a public university or TVET college",
      "SASSA grant recipient",
    ],
    deadline: "30 November 2025",
    link: "https://www.nsfas.org.za",
  },
  {
    id: "bursary-4",
    title: "Anglo American Mining Bursary",
    provider: "Anglo American",
    amount: "R90,000 per year",
    field: "Mining Engineering",
    description: "Bursary for mining engineering students with strong academic performance",
    eligibility: [
      "South African citizen",
      "Studying Mining Engineering",
      "Minimum 65% average",
      "Willingness to work in mining sector",
    ],
    deadline: "31 July 2025",
    link: "https://www.angloamerican.com/careers/bursaries",
  },
  {
    id: "bursary-5",
    title: "Discovery Health Sciences Bursary",
    provider: "Discovery Limited",
    amount: "R60,000 per year",
    field: "Medicine and Health Sciences",
    description: "Bursary for medical and health science students pursuing careers in healthcare",
    eligibility: [
      "South African citizen",
      "Studying Medicine, Nursing, or Allied Health",
      "Minimum 70% average",
      "Passion for healthcare",
    ],
    deadline: "30 September 2025",
    link: "https://www.discovery.co.za/careers/bursaries",
  },
  {
    id: "bursary-6",
    title: "ABSA Accounting Bursary",
    provider: "ABSA Bank",
    amount: "R55,000 per year",
    field: "Accounting and Finance",
    description: "Financial support for accounting students aiming to become chartered accountants",
    eligibility: [
      "South African citizen",
      "Studying towards CA(SA)",
      "Minimum 65% average",
      "Strong analytical skills",
    ],
    deadline: "31 August 2025",
    link: "https://www.absa.co.za/careers/bursaries",
  },
  {
    id: "bursary-7",
    title: "Transnet Engineering Bursary",
    provider: "Transnet SOC Ltd",
    amount: "R70,000 per year",
    field: "Civil Engineering",
    description: "Bursary for civil engineering students interested in infrastructure development",
    eligibility: [
      "South African citizen",
      "Studying Civil Engineering",
      "Minimum 60% average",
      "Interest in transport infrastructure",
    ],
    deadline: "30 June 2025",
    link: "https://www.transnet.net/careers/bursaries",
  },
  {
    id: "bursary-8",
    title: "Standard Bank IT Bursary",
    provider: "Standard Bank",
    amount: "R50,000 per year",
    field: "Information Technology",
    description: "Bursary for IT and computer science students with strong technical skills",
    eligibility: [
      "South African citizen",
      "Studying IT or Computer Science",
      "Minimum 65% average",
      "Passion for technology",
    ],
    deadline: "31 July 2025",
    link: "https://www.standardbank.co.za/careers/bursaries",
  },
  {
    id: "bursary-9",
    title: "Nedbank Commerce Bursary",
    provider: "Nedbank Limited",
    amount: "R45,000 per year",
    field: "Commerce and Business",
    description: "Financial assistance for commerce students pursuing careers in banking and finance",
    eligibility: [
      "South African citizen",
      "Studying BCom or related field",
      "Minimum 60% average",
      "Leadership potential",
    ],
    deadline: "30 September 2025",
    link: "https://www.nedbank.co.za/careers/bursaries",
  },
  {
    id: "bursary-10",
    title: "Deloitte Audit Bursary",
    provider: "Deloitte South Africa",
    amount: "R65,000 per year",
    field: "Auditing",
    description: "Bursary for students pursuing careers in auditing and assurance",
    eligibility: [
      "South African citizen",
      "Studying towards CA(SA) or related qualification",
      "Minimum 70% average",
      "Strong communication skills",
    ],
    deadline: "31 August 2025",
    link: "https://www.deloitte.com/za/careers/bursaries",
  },
  {
    id: "bursary-11",
    title: "PwC Tax Bursary",
    provider: "PricewaterhouseCoopers",
    amount: "R60,000 per year",
    field: "Taxation",
    description: "Financial support for students interested in tax and advisory services",
    eligibility: ["South African citizen", "Studying Accounting or Tax", "Minimum 65% average", "Analytical mindset"],
    deadline: "30 July 2025",
    link: "https://www.pwc.co.za/careers/bursaries",
  },
  {
    id: "bursary-12",
    title: "KPMG Audit Bursary",
    provider: "KPMG South Africa",
    amount: "R58,000 per year",
    field: "Auditing and Accounting",
    description: "Bursary for accounting students with strong academic records",
    eligibility: ["South African citizen", "Studying towards CA(SA)", "Minimum 68% average", "Leadership qualities"],
    deadline: "31 August 2025",
    link: "https://www.kpmg.co.za/careers/bursaries",
  },
  {
    id: "bursary-13",
    title: "EY Business Advisory Bursary",
    provider: "Ernst & Young",
    amount: "R62,000 per year",
    field: "Business and Finance",
    description: "Financial assistance for students pursuing careers in business advisory",
    eligibility: [
      "South African citizen",
      "Studying BCom or related field",
      "Minimum 65% average",
      "Problem-solving skills",
    ],
    deadline: "30 September 2025",
    link: "https://www.ey.com/za/careers/bursaries",
  },
  {
    id: "bursary-14",
    title: "Shoprite Education Bursary",
    provider: "Shoprite Holdings",
    amount: "R40,000 per year",
    field: "Education and Teaching",
    description: "Bursary for students pursuing teaching qualifications",
    eligibility: [
      "South African citizen",
      "Studying towards teaching qualification",
      "Minimum 60% average",
      "Passion for education",
    ],
    deadline: "31 July 2025",
    link: "https://www.shopriteholdings.co.za/careers/bursaries",
  },
  {
    id: "bursary-15",
    title: "SAB Agriculture Bursary",
    provider: "South African Breweries",
    amount: "R55,000 per year",
    field: "Agriculture",
    description: "Financial support for agriculture students interested in sustainable farming",
    eligibility: [
      "South African citizen",
      "Studying Agriculture or related field",
      "Minimum 60% average",
      "Interest in agribusiness",
    ],
    deadline: "30 June 2025",
    link: "https://www.sab.co.za/careers/bursaries",
  },
  {
    id: "bursary-16",
    title: "Vodacom ICT Bursary",
    provider: "Vodacom Group",
    amount: "R52,000 per year",
    field: "Information and Communications Technology",
    description: "Bursary for ICT students with strong technical aptitude",
    eligibility: [
      "South African citizen",
      "Studying ICT or related field",
      "Minimum 65% average",
      "Innovation mindset",
    ],
    deadline: "31 August 2025",
    link: "https://www.vodacom.co.za/careers/bursaries",
  },
  {
    id: "bursary-17",
    title: "MTN Technology Bursary",
    provider: "MTN South Africa",
    amount: "R50,000 per year",
    field: "Telecommunications",
    description: "Financial assistance for students pursuing careers in telecommunications",
    eligibility: [
      "South African citizen",
      "Studying Engineering or ICT",
      "Minimum 60% average",
      "Interest in mobile technology",
    ],
    deadline: "30 July 2025",
    link: "https://www.mtn.co.za/careers/bursaries",
  },
  {
    id: "bursary-18",
    title: "Telkom Engineering Bursary",
    provider: "Telkom SA SOC Ltd",
    amount: "R65,000 per year",
    field: "Telecommunications Engineering",
    description: "Bursary for engineering students interested in telecommunications infrastructure",
    eligibility: [
      "South African citizen",
      "Studying Electrical or Electronic Engineering",
      "Minimum 65% average",
      "Technical aptitude",
    ],
    deadline: "31 August 2025",
    link: "https://www.telkom.co.za/careers/bursaries",
  },
  {
    id: "bursary-19",
    title: "Rand Water Engineering Bursary",
    provider: "Rand Water",
    amount: "R60,000 per year",
    field: "Water Engineering",
    description: "Financial support for engineering students interested in water infrastructure",
    eligibility: [
      "South African citizen",
      "Studying Civil or Chemical Engineering",
      "Minimum 60% average",
      "Interest in water management",
    ],
    deadline: "30 June 2025",
    link: "https://www.randwater.co.za/careers/bursaries",
  },
  {
    id: "bursary-20",
    title: "Siemens Mechatronics Bursary",
    provider: "Siemens South Africa",
    amount: "R70,000 per year",
    field: "Mechatronics",
    description: "Bursary for mechatronics and automation engineering students",
    eligibility: [
      "South African citizen",
      "Studying Mechatronics or related field",
      "Minimum 65% average",
      "Interest in automation",
    ],
    deadline: "31 July 2025",
    link: "https://www.siemens.co.za/careers/bursaries",
  },
  {
    id: "bursary-21",
    title: "BMW Mechanical Engineering Bursary",
    provider: "BMW South Africa",
    amount: "R75,000 per year",
    field: "Mechanical Engineering",
    description: "Financial assistance for mechanical engineering students with automotive interest",
    eligibility: [
      "South African citizen",
      "Studying Mechanical Engineering",
      "Minimum 70% average",
      "Passion for automotive technology",
    ],
    deadline: "30 August 2025",
    link: "https://www.bmw.co.za/careers/bursaries",
  },
  {
    id: "bursary-22",
    title: "Mercedes-Benz Engineering Bursary",
    provider: "Mercedes-Benz South Africa",
    amount: "R72,000 per year",
    field: "Automotive Engineering",
    description: "Bursary for engineering students interested in automotive manufacturing",
    eligibility: [
      "South African citizen",
      "Studying Engineering",
      "Minimum 68% average",
      "Interest in automotive industry",
    ],
    deadline: "31 July 2025",
    link: "https://www.mercedes-benz.co.za/careers/bursaries",
  },
  {
    id: "bursary-23",
    title: "SAA Aviation Bursary",
    provider: "South African Airways",
    amount: "R85,000 per year",
    field: "Aviation",
    description: "Financial support for students pursuing careers in aviation",
    eligibility: [
      "South African citizen",
      "Studying Aviation or Aeronautical Engineering",
      "Minimum 70% average",
      "Medical fitness for aviation",
    ],
    deadline: "30 June 2025",
    link: "https://www.flysaa.com/careers/bursaries",
  },
  {
    id: "bursary-24",
    title: "Airports Company Aviation Bursary",
    provider: "Airports Company South Africa",
    amount: "R68,000 per year",
    field: "Aviation Management",
    description: "Bursary for students interested in airport operations and management",
    eligibility: [
      "South African citizen",
      "Studying Aviation Management or related field",
      "Minimum 65% average",
      "Leadership potential",
    ],
    deadline: "31 August 2025",
    link: "https://www.airports.co.za/careers/bursaries",
  },
  {
    id: "bursary-25",
    title: "Transnet Maritime Bursary",
    provider: "Transnet National Ports Authority",
    amount: "R70,000 per year",
    field: "Maritime Studies",
    description: "Financial assistance for students pursuing maritime qualifications",
    eligibility: [
      "South African citizen",
      "Studying Maritime Studies or Marine Engineering",
      "Minimum 60% average",
      "Interest in shipping industry",
    ],
    deadline: "30 July 2025",
    link: "https://www.transnetnationalportsauthority.net/careers/bursaries",
  },
  {
    id: "bursary-26",
    title: "Sun International Hospitality Bursary",
    provider: "Sun International",
    amount: "R45,000 per year",
    field: "Hospitality Management",
    description: "Bursary for students pursuing careers in hospitality and tourism",
    eligibility: [
      "South African citizen",
      "Studying Hospitality Management",
      "Minimum 60% average",
      "Customer service orientation",
    ],
    deadline: "31 August 2025",
    link: "https://www.suninternational.com/careers/bursaries",
  },
  {
    id: "bursary-27",
    title: "Tsogo Sun Tourism Bursary",
    provider: "Tsogo Sun Hotels",
    amount: "R42,000 per year",
    field: "Tourism Management",
    description: "Financial support for tourism management students",
    eligibility: [
      "South African citizen",
      "Studying Tourism or Hospitality",
      "Minimum 58% average",
      "Passion for tourism industry",
    ],
    deadline: "30 September 2025",
    link: "https://www.tsogosun.com/careers/bursaries",
  },
  {
    id: "bursary-28",
    title: "Unilever Marketing Bursary",
    provider: "Unilever South Africa",
    amount: "R50,000 per year",
    field: "Marketing and Communications",
    description: "Bursary for marketing and communications students with creative flair",
    eligibility: [
      "South African citizen",
      "Studying Marketing or Communications",
      "Minimum 65% average",
      "Creative thinking",
    ],
    deadline: "31 July 2025",
    link: "https://www.unilever.co.za/careers/bursaries",
  },
  {
    id: "bursary-29",
    title: "Coca-Cola Business Bursary",
    provider: "Coca-Cola Beverages South Africa",
    amount: "R48,000 per year",
    field: "Business Management",
    description: "Financial assistance for business management students",
    eligibility: [
      "South African citizen",
      "Studying Business Management",
      "Minimum 60% average",
      "Entrepreneurial mindset",
    ],
    deadline: "30 August 2025",
    link: "https://www.ccbsa.co.za/careers/bursaries",
  },
  {
    id: "bursary-30",
    title: "Tiger Brands Food Science Bursary",
    provider: "Tiger Brands Limited",
    amount: "R55,000 per year",
    field: "Food Science and Technology",
    description: "Bursary for food science students interested in food manufacturing",
    eligibility: [
      "South African citizen",
      "Studying Food Science or Technology",
      "Minimum 65% average",
      "Interest in food industry",
    ],
    deadline: "31 July 2025",
    link: "https://www.tigerbrands.com/careers/bursaries",
  },
  {
    id: "bursary-31",
    title: "Department of Justice Law Bursary",
    provider: "Department of Justice and Constitutional Development",
    amount: "R50,000 per year",
    field: "Law",
    description: "Government bursary for law students committed to public service",
    eligibility: ["South African citizen", "Studying LLB", "Minimum 65% average", "Commitment to work for DOJ"],
    deadline: "30 September 2025",
    link: "https://www.justice.gov.za/careers/bursaries",
  },
  {
    id: "bursary-32",
    title: "Legal Aid South Africa Bursary",
    provider: "Legal Aid South Africa",
    amount: "R45,000 per year",
    field: "Law",
    description: "Financial support for law students interested in legal aid work",
    eligibility: ["South African citizen", "Studying LLB", "Minimum 60% average", "Passion for social justice"],
    deadline: "31 August 2025",
    link: "https://www.legal-aid.co.za/careers/bursaries",
  },
  {
    id: "bursary-33",
    title: "SABC Media Studies Bursary",
    provider: "South African Broadcasting Corporation",
    amount: "R40,000 per year",
    field: "Media and Communications",
    description: "Bursary for media studies students interested in broadcasting",
    eligibility: [
      "South African citizen",
      "Studying Media Studies or Journalism",
      "Minimum 60% average",
      "Communication skills",
    ],
    deadline: "30 July 2025",
    link: "https://www.sabc.co.za/careers/bursaries",
  },
  {
    id: "bursary-34",
    title: "Independent Media Journalism Bursary",
    provider: "Independent Media",
    amount: "R38,000 per year",
    field: "Journalism",
    description: "Financial assistance for journalism students with writing talent",
    eligibility: ["South African citizen", "Studying Journalism", "Minimum 58% average", "Strong writing skills"],
    deadline: "31 August 2025",
    link: "https://www.independentmedia.co.za/careers/bursaries",
  },
  {
    id: "bursary-35",
    title: "Department of Arts and Culture Bursary",
    provider: "Department of Arts and Culture",
    amount: "R35,000 per year",
    field: "Arts and Humanities",
    description: "Government bursary for arts and culture students",
    eligibility: ["South African citizen", "Studying Arts, Music, or Drama", "Minimum 55% average", "Artistic talent"],
    deadline: "30 September 2025",
    link: "https://www.dac.gov.za/careers/bursaries",
  },
]

export async function GET() {
  try {
    if (bursariesCache && Date.now() - bursariesCache.timestamp < CACHE_DURATION) {
      return NextResponse.json(
        {
          success: true,
          bursaries: bursariesCache.data,
          totalCount: bursariesCache.data.length,
          cached: true,
          cacheAge: Math.floor((Date.now() - bursariesCache.timestamp) / 1000 / 60),
          nextRefresh: Math.floor((CACHE_DURATION - (Date.now() - bursariesCache.timestamp)) / 1000 / 60),
        },
        {
          headers: {
            "Cache-Control": "public, s-maxage=86400, stale-while-revalidate=43200",
          },
        },
      )
    }

    const bursaries = BURSARIES_DATA

    // Update cache
    bursariesCache = {
      data: bursaries,
      timestamp: Date.now(),
    }

    return NextResponse.json(
      {
        success: true,
        bursaries,
        totalCount: bursaries.length,
        cached: false,
        source: "Curated South African Bursaries",
      },
      {
        headers: {
          "Cache-Control": "public, s-maxage=86400, stale-while-revalidate=43200",
        },
      },
    )
  } catch (error) {
    console.error("Bursaries API Error:", error)

    // Return cached data if available, even if expired
    if (bursariesCache) {
      return NextResponse.json({
        success: true,
        bursaries: bursariesCache.data,
        totalCount: bursariesCache.data.length,
        cached: true,
        stale: true,
        message: "Using cached bursaries due to API error",
      })
    }

    return NextResponse.json(
      {
        success: false,
        error: "Failed to fetch bursaries",
        message: "Unable to load bursaries at this time",
      },
      { status: 500 },
    )
  }
}
