import { CalendarEvent } from "./types"

export const events2025: CalendarEvent[] = [
    { date: new Date(2025, 0, 1), name: "New Year's Day", type: "public" },
    { date: new Date(2025, 2, 21), name: "Human Rights Day", type: "public" },
    { date: new Date(2025, 3, 18), name: "Good Friday", type: "public" },
    { date: new Date(2025, 3, 21), name: "Family Day", type: "public" },
    { date: new Date(2025, 3, 27), name: "Freedom Day", type: "public" },
    { date: new Date(2025, 4, 1), name: "Workers' Day", type: "public" },
    { date: new Date(2025, 5, 16), name: "Youth Day", type: "public" },
    { date: new Date(2025, 7, 9), name: "National Women's Day", type: "public" },
    { date: new Date(2025, 8, 24), name: "Heritage Day", type: "public" },
    { date: new Date(2025, 11, 16), name: "Day of Reconciliation", type: "public" },
    { date: new Date(2025, 11, 25), name: "Christmas Day", type: "public" },
    { date: new Date(2025, 11, 26), name: "Day of Goodwill", type: "public" },
    { date: new Date(2025, 0, 15), name: "Schools Reopen", type: "academic" },
    { date: new Date(2025, 2, 28), name: "Term 1 Ends", type: "academic" },
    { date: new Date(2025, 3, 14), name: "Term 2 Begins", type: "academic" },
    { date: new Date(2025, 5, 27), name: "Term 2 Ends", type: "academic" },
    { date: new Date(2025, 6, 14), name: "Term 3 Begins", type: "academic" },
    { date: new Date(2025, 8, 19), name: "Term 3 Ends", type: "academic" },
    { date: new Date(2025, 9, 6), name: "Term 4 Begins", type: "academic" },
    { date: new Date(2025, 11, 12), name: "Schools Close", type: "academic" },
    { date: new Date(2025, 9, 17), name: "Matric Pledge Signing", type: "exam", time: "10:00", description: "Matric learners participate in pledge signing ceremony" },
    { date: new Date(2025, 9, 20), name: "NSC Exams Begin", type: "exam", time: "09:00", description: "National Senior Certificate examinations commence" },
    { date: new Date(2025, 9, 24), name: "Information Technology P2", type: "exam", time: "09:00", description: "IT P2 Theory (3hrs)" },
    { date: new Date(2025, 9, 27), name: "Dance Studies", type: "exam", time: "09:00", description: "Dance Studies, Electrical Tech" },
    { date: new Date(2025, 9, 27), name: "Languages P1", type: "exam", time: "14:00", description: "Portuguese/German/Hebrew P1" },
    { date: new Date(2025, 9, 28), name: "History P1", type: "exam", time: "09:00", description: "History P1 (3hrs), Maritime Economics" },
    { date: new Date(2025, 9, 28), name: "Various Languages P1", type: "exam", time: "14:00", description: "Various Languages P1" },
    { date: new Date(2025, 9, 29), name: "Afrikaans P1", type: "exam", time: "09:00", description: "Afrikaans HL and FAL P1 (2hrs)" },
    { date: new Date(2025, 9, 30), name: "Mathematics P1", type: "exam", time: "09:00", description: "Mathematics P1 (3hrs), Mathematical Literacy P1 (3hrs)" },
    { date: new Date(2025, 9, 31), name: "Mathematics P2", type: "exam", time: "09:00", description: "Mathematics P2 (3hrs)" },
    { date: new Date(2025, 9, 31), name: "Mathematical Literacy P2", type: "exam", time: "14:00", description: "Mathematical Literacy P2 (3hrs)" },
    { date: new Date(2025, 10, 3), name: "English P1", type: "exam", time: "09:00", description: "English HL/FAL P1 (2hrs)" },
    { date: new Date(2025, 10, 3), name: "Engineering Graphics P1", type: "exam", time: "14:00", description: "Engineering Graphics P1 (3hrs)" },
    { date: new Date(2025, 10, 4), name: "African Languages P1", type: "exam", time: "09:00", description: "isiZulu, isiXhosa, Siswati, isiNdebele P1" },
    { date: new Date(2025, 10, 4), name: "Engineering Graphics P2", type: "exam", time: "14:00", description: "Engineering Graphics P2" },
    { date: new Date(2025, 10, 5), name: "Agricultural Science P1", type: "exam", time: "09:00", description: "Agricultural Science P1 (2½hrs), Nautical Science P1" },
    { date: new Date(2025, 10, 6), name: "Agricultural Science P2", type: "exam", time: "09:00", description: "Agricultural Science P2 (2½hrs)" },
    { date: new Date(2025, 10, 6), name: "Visual Arts", type: "exam", time: "14:00", description: "Visual Arts (3hrs)" },
    { date: new Date(2025, 10, 7), name: "Afrikaans P2", type: "exam", time: "09:00", description: "Afrikaans P2" },
    { date: new Date(2025, 10, 7), name: "African Languages P1", type: "exam", time: "14:00", description: "Sepedi/Sesotho/Setswana/Xitsonga/Tshivenda P1" },
    { date: new Date(2025, 10, 10), name: "Economics", type: "exam", time: "09:00", description: "Economics (3hrs)" },
    { date: new Date(2025, 10, 10), name: "Mechanical Technology", type: "exam", time: "14:00", description: "Mechanical Technology (3hrs)" },
    { date: new Date(2025, 10, 11), name: "English P2", type: "exam", time: "09:00", description: "English P2" },
    { date: new Date(2025, 10, 11), name: "Languages P3", type: "exam", time: "14:00", description: "Portuguese/German P3" },
    { date: new Date(2025, 10, 12), name: "Physical Science P1", type: "exam", time: "09:00", description: "Physical Science (Physics) P1 (3hrs)" },
    { date: new Date(2025, 10, 13), name: "Physical Science P2", type: "exam", time: "09:00", description: "Physical Science (Chemistry) P2 (3hrs)" },
    { date: new Date(2025, 10, 13), name: "Various Languages P3", type: "exam", time: "14:00", description: "Various Languages P3" },
    { date: new Date(2025, 10, 14), name: "English P3", type: "exam", time: "09:00", description: "English P3 (2½hrs)" },
    { date: new Date(2025, 10, 14), name: "Music P1", type: "exam", time: "14:00", description: "Music P1 Theory (3hrs)" },
    { date: new Date(2025, 10, 17), name: "History P2", type: "exam", time: "09:00", description: "History P2 (3hrs)" },
    { date: new Date(2025, 10, 17), name: "Agricultural Technology", type: "exam", time: "14:00", description: "Agricultural Technology (3hrs)" },
    { date: new Date(2025, 10, 18), name: "Life Sciences P1", type: "exam", time: "09:00", description: "Life Sciences P1 (2½hrs)" },
    { date: new Date(2025, 10, 18), name: "Afrikaans P3", type: "exam", time: "14:00", description: "Afrikaans P3 (2½hrs)" },
    { date: new Date(2025, 10, 19), name: "Life Sciences P2", type: "exam", time: "09:00", description: "Life Sciences P2 (2½hrs)" },
    { date: new Date(2025, 10, 19), name: "Religion Studies", type: "exam", time: "14:00", description: "Religion Studies P1 (2hrs)" },
    { date: new Date(2025, 10, 20), name: "Tourism", type: "exam", time: "09:00", description: "Tourism (3hrs)" },
    { date: new Date(2025, 10, 20), name: "Mathematics P3", type: "exam", time: "14:00", description: "Mathematics P3 (2hrs)" },
    { date: new Date(2025, 10, 21), name: "Accounting", type: "exam", time: "09:00", description: "Accounting (3hrs)" },
    { date: new Date(2025, 10, 21), name: "Agriculture Management", type: "exam", time: "14:00", description: "Agriculture Management Practices (2½hrs)" },
    { date: new Date(2025, 10, 24), name: "African Languages P2", type: "exam", time: "09:00", description: "isiZulu/isiXhosa/Siswati/isiNdebele P2" },
    { date: new Date(2025, 10, 24), name: "Design", type: "exam", time: "14:00", description: "Design (3hrs)" },
    { date: new Date(2025, 10, 25), name: "NSC Exams End", type: "exam", time: "17:00", description: "National Senior Certificate examinations conclude" },
    { date: new Date(2025, 4, 12), name: "May/June Supplementary Exams Begin", type: "exam", time: "09:00", description: "Supplementary examinations for NSC candidates" },
    { date: new Date(2025, 5, 20), name: "May/June Supplementary Exams End", type: "exam", time: "17:00", description: "Supplementary examinations conclude" },
]
