import { CalendarEvent } from "./types"

export const events2026: CalendarEvent[] = [
    { date: new Date(2026, 0, 1), name: "New Year's Day", type: "public", description: "The first day of the year according to the Gregorian calendar. A time for fresh starts and celebrations.", url: "https://en.wikipedia.org/wiki/New_Year%27s_Day" },
    { date: new Date(2026, 2, 21), name: "Human Rights Day", type: "public", description: "Commemorates the 1960 Sharpeville massacre and celebrates South Africa's constitutional rights.", url: "https://en.wikipedia.org/wiki/Human_Rights_Day_(South_Africa)" },
    { date: new Date(2026, 3, 3), name: "Good Friday", type: "public", description: "A Christian holiday commemorating the crucifixion of Jesus and his death.", url: "https://en.wikipedia.org/wiki/Good_Friday" },
    { date: new Date(2026, 3, 6), name: "Family Day", type: "public", description: "Previously known as Easter Monday, a day encouraging families to spend time together.", url: "https://en.wikipedia.org/wiki/Easter_Monday" },
    { date: new Date(2026, 3, 27), name: "Freedom Day", type: "public", description: "Commemorates South Africa's first non-racial democratic elections held in 1994.", url: "https://en.wikipedia.org/wiki/Freedom_Day_(South_Africa)" },
    { date: new Date(2026, 4, 1), name: "Workers' Day", type: "public", description: "Celebrates the historical struggles and gains made by workers and the labor movement.", url: "https://en.wikipedia.org/wiki/International_Workers%27_Day" },
    { date: new Date(2026, 5, 15), name: "Special School Holiday", type: "public", description: "An extra holiday granted by the educational department to extend the weekend.", url: "" },
    { date: new Date(2026, 5, 16), name: "Youth Day", type: "public", description: "Commemorates the youth who protested in the 1976 Soweto Uprising against the Bantu Education Act.", url: "https://en.wikipedia.org/wiki/Youth_Day_(South_Africa)" },
    { date: new Date(2026, 7, 9), name: "National Women's Day", type: "public", description: "Commemorates the 1956 march of women to the Union Buildings to petition against the pass laws.", url: "https://en.wikipedia.org/wiki/National_Women%27s_Day" },
    { date: new Date(2026, 7, 10), name: "Public Holiday", type: "public", description: "A supplementary day off granted when a public holiday falls on a Sunday.", url: "" },
    { date: new Date(2026, 8, 24), name: "Heritage Day", type: "public", description: "A day for South Africans to celebrate their rich cultural wealth and diversity (also known as Braai Day).", url: "https://en.wikipedia.org/wiki/Heritage_Day_(South_Africa)" },
    { date: new Date(2026, 11, 16), name: "Day of Reconciliation", type: "public", description: "Promotes unity and reconciliation across the country's diverse cultures alongside historical significance.", url: "https://en.wikipedia.org/wiki/Day_of_Reconciliation" },
    { date: new Date(2026, 11, 25), name: "Christmas Day", type: "public", description: "A Christian holiday honoring the birth of Jesus Christ, widely celebrated globally.", url: "https://en.wikipedia.org/wiki/Christmas" },
    { date: new Date(2026, 11, 26), name: "Day of Goodwill", type: "public", description: "A day extending the Christmas festivities, traditionally associated with Boxing Day.", url: "https://en.wikipedia.org/wiki/Boxing_Day" },
    { date: new Date(2026, 0, 14), name: "Schools Reopen", type: "academic" },
    { date: new Date(2026, 2, 27), name: "Term 1 Ends", type: "academic" },
    { date: new Date(2026, 3, 8), name: "Term 2 Begins", type: "academic" },
    { date: new Date(2026, 5, 26), name: "Term 2 Ends", type: "academic" },
    { date: new Date(2026, 6, 21), name: "Term 3 Begins", type: "academic" },
    { date: new Date(2026, 8, 23), name: "Term 3 Ends", type: "academic" },
    { date: new Date(2026, 9, 6), name: "Term 4 Begins", type: "academic" },
    { date: new Date(2026, 11, 11), name: "Schools Close", type: "academic" },
]
